name: Hello Workflow

on: push

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v7

      - name: Print greeting
        run: echo "Hello from Github actions"

      - name: Print current date and time
        run: date

      - name: Print triggering branch
        run: echo "Triggered by branch -> ${{ github.ref_name }}"

      - name: List files in repo
        run: ls -la 

      - name: Print runer OS
        run: echo " Runner OS -> ${{ runner.os }}"

      - name: Intentional break code
        run: exit 1
