name: Manual deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Enviroment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  manual-run:
    runs-on: ubuntu-latest
    steps:
      - name: Print input 
        run: echo '"Deploying to environment ${{ inputs.environment }}"'
