name: Nightly Job CRON

on:
  schedule:
    - cron: '36 14 * * *'

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Running scheduled nightly job at $(date -u)"
