name: Nightly Job CRON

# Disabled below scheduled block  for testing day-42 practice
# on:
#   schedule:
#     - cron: '36 14 * * *'

on:
  workflow_dispatch:

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Running scheduled nightly job at $(date -u)"
